### ISSUE TITLE
volley folder empty in fork with new fancy UI stuff like album art etc 

### ISSUE THREAD

**Issue by luwo1701** [luwo1701/Party-Queue#15]
Hey ya'll I know it's Saturday so feel free to ignore this till the week starts. Incase ya'll are working on the project though Daniels current master that has all the fancy UI stuff didn't upload the contents of his volley folder for some reason. If you clone his you can then move into that directory remove the old volley directory and using the clone command below add a new directory with the needed library files. Worked for me.

git clone https://android.googlesource.com/platform/frameworks/volley

@busunkim96 @cosh9041 

Cheers Yall
Have a good weekend. 
Luke.
:muscle: :metal:

**Comment by cosh9041** [comment]
We'll leave this open for future reference
