### ISSUE TITLE
UI confusion... xml file doesn't seem to have layout...

### ISSUE THREAD

**Issue by luwo1701** [luwo1701/Party-Queue#16]
I understood previously the xml file had the UI code in it but there is very little code in there none of which seems to describe the buttons and text boxes we have in our app. It seems to me after looking at the manifest.xml file that app:theme and <intent-filter> may have something to do with it. 

@daniel-j-henderson

**Comment by daniel-j-henderson** [comment]
The manifest.xml file has nothing to do with the layout or UI of any part of the app. The manifest just tells the OS about all the activities and processes and permissions the app will use. Each activity's layout it in its own xml file in res/layouts/, so looking there should clear that up

**Comment by luwo1701** [comment]
thanks @daniel-j-henderson :metal:
