### ISSUE TITLE
We Need a Backend to the service

### ISSUE THREAD

**Issue by cosh9041** [luwo1701/Party-Queue#2]
We need to develop a backend database for the service

**Comment by daniel-j-henderson** [comment]
Sounds like this needs to: 1. Store user information and party metadata and song queue in some sort of database, prols mysql. 2. implement some interface, prols json, for the android app to query that database for user information and the next song URI. 3. Also implement an interface that allows a user to search/add songs.

**Comment by cosh9041** [comment]
yep that sounds about right
