### ISSUE TITLE
Backend tutorial

### ISSUE THREAD

**Issue by luwo1701** [luwo1701/Party-Queue#21]
Daniel and I are working on the app and tried to look over the back end stuff @cosh9041  worked on but are pretty confused. We're thinking it would be more efficient if we got together and corwin explained it to all of us
@daniel-j-henderson @busunkim96

**Comment by busunkim96** [comment]
Are there any pages/activities that need to be added to prepare the app for the backend or is the frontend good at this point? I'd like to do some work on this before our meeting Wednesday. 

@daniel-j-henderson  @cosh9041  @luwo1701

**Comment by cosh9041** [comment]
Let's do this tomorrow afternoon/evening and/or during our meeting on wednesday.
