### ISSUE TITLE
Make Queue Activity

### ISSUE THREAD

**Issue by busunkim96** [luwo1701/Party-Queue#24]
We need an activity where songs can be voted up/down.

**Comment by daniel-j-henderson** [comment]
Looks like I can't actually implement the voting right now because the `v.getId()` in the viewHolder class is a random number, not its index in the list @busunkim96

**Comment by busunkim96** [comment]
`v.getId()` just identifies the button itself in the layout.  It's to make sure that each of the buttons is only associated with one row. (I thought it identified position when I first worked on it but noticed that it's a random number as you pointed out). 

Things that identify the song itself are`song_uri`and `title`. Is this sufficient for talking to the backend or do you need something else? Any click for a upvote/downvote should probably trigger a refresh of the layout (`Recycler_View_Adapter.this.notifyDataSetChanged();`) or a full reload. @daniel-j-henderson

**Comment by busunkim96** [comment]
@daniel-j-henderson 

I see now that the backend wants the position in the array. I'll work on the modifications to store that and send them to you.
