### ISSUE TITLE
Queue activity

### ISSUE THREAD

**Issue by luwo1701** [luwo1701/Party-Queue#29]
Hey @busunkim96 where are we at with the queue activity. I'd like to work on it today and was wondering  if you have anything I can build off of. 
Cheers :beers:

**Comment by busunkim96** [comment]
Hi @luwo1701. My fork's master has the work I've gotten done up till now (see QueueActivity). I was trying to add the same search bar from the Spotify Activity but was having issues getting the dropdown menu to appear. Since you implemented it, it'll probably be quicker for you.

**Comment by busunkim96** [comment]
@luwo1701 I forgot to mention this, but I commented out line with the original intent to SpotifyActivity after the login and changed it to go to QueueActivity so it was faster to test on my end.
