### ISSUE TITLE
Merging busuns branch with master

### ISSUE THREAD

**Issue by luwo1701** [luwo1701/Party-Queue#30]
I've been trying for a while now to get busuns branch to merge with our current working branch and there's some really funky stuff going on. When I used a diff GUI to try to see where we were differing it showed a bunch of symbols similar to what you'd see if you try to open a pdf in terminal. What it comes down to was I couldn't decipher it. Maybe someone else can give it a look?
@busunkim96 @daniel-j-henderson @cosh9041

**Comment by busunkim96** [comment]
Could you tell me what file(s) were being weird? @luwo1701

**Comment by luwo1701** [comment]
I'm not at my computer anymore.

**Comment by busunkim96** [comment]
OK, I got the dropdown to work in QueueActivity so I'll work on merging it with master locally.

**Comment by busunkim96** [comment]
Looks like it was just something in library files. I accepted the state of the file from the current master (with git checkout --theirs path_name) and things still look to be working smoothly on my end. I pushed the merged branch to my master. @luwo1701 @cosh9041 @daniel-j-henderson
